# Form implementation generated from reading ui file 'simulation.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.no_of_days = QtWidgets.QSlider(parent=self.centralwidget)
        self.no_of_days.setGeometry(QtCore.QRect(20, 80, 160, 16))
        self.no_of_days.setMinimum(1)
        self.no_of_days.setMaximum(365)
        self.no_of_days.setSingleStep(5)
        self.no_of_days.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.no_of_days.setObjectName("no_of_days")
        self.initial = QtWidgets.QSlider(parent=self.centralwidget)
        self.initial.setGeometry(QtCore.QRect(20, 110, 160, 16))
        self.initial.setMinimum(1000)
        self.initial.setMaximum(1000000)
        self.initial.setSingleStep(10000)
        self.initial.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.initial.setObjectName("initial")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 80, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 110, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 140, 61, 16))
        self.label_3.setObjectName("label_3")
        self.no_of_sims = QtWidgets.QSlider(parent=self.centralwidget)
        self.no_of_sims.setGeometry(QtCore.QRect(20, 140, 160, 16))
        self.no_of_sims.setMinimum(1)
        self.no_of_sims.setMaximum(200)
        self.no_of_sims.setSingleStep(10)
        self.no_of_sims.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.no_of_sims.setObjectName("no_of_sims")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 190, 681, 391))
        self.graphicsView.setObjectName("graphicsView")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(280, 20, 281, 81))
        self.textBrowser.setObjectName("textBrowser")
        self.simulate_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.simulate_button.setGeometry(QtCore.QRect(590, 30, 101, 51))
        self.simulate_button.setObjectName("simulate_button")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 61, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox_stock = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_stock.setGeometry(QtCore.QRect(80, 30, 121, 22))
        self.comboBox_stock.setObjectName("comboBox_stock")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "No_of_Days"))
        self.label_2.setText(_translate("MainWindow", "Initial Amount"))
        self.label_3.setText(_translate("MainWindow", "No_of_Sims"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.simulate_button.setText(_translate("MainWindow", "simulate"))
        self.label_4.setText(_translate("MainWindow", "Stock Name : "))
